export default [
  {
    'Employee No': '32224',
    Name: 'ANISH THOMAS',
    Department: 'Office Of The Nursing Director',
    Branch: 'Khobar',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Khobar - Building A Main Entrance',
    HOD: 'NA',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32256',
    Name: 'BabulAbbas',
    Department: 'General Housekeeping Department - Jubail',
    Branch: 'Jubail',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Multi-Location',
    'Assigned Location':
      'Jubail - Transportation Office, AMC Jubail Main Building - Gnd Flr Staff Entrance 2',
    HOD: 'NA',
    'Early Check-In Allowed': 'No',
    Status: 'Active',
  },
  {
    'Employee No': '32220',
    Name: 'BATOULALMUSAWI',
    Department: 'General Laboratory',
    Branch: 'Hofuf',
    Role: '',
    'Attendance Method': 'Computer',
    'Mac Address': ' 643150303E12,6C4B9096CA16,D4BED98B7968',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Hofuf - Building A Main Entrance',
    HOD: 'Mohamad Almhdy Attya Mohamad',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32264',
    Name: 'BilalSuriya',
    Department: 'Facility Engineering Dept - Dammam',
    Branch: 'Dammam',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Multi-Location',
    'Assigned Location': 'Dammam - AST Main Entrance, Dammam - OR Building',
    HOD: 'Ibrahim Abdulrahman Bousbait',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32225',
    Name: 'CHARLY THOMAS',
    Department: 'Office Of The Nursing Director',
    Branch: 'Khobar',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Khobar - Building A Main Entrance',
    HOD: 'NA',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32209',
    Name: 'FATIMAHALBELADI',
    Department: 'General Housekeeping Department',
    Branch: 'Hofuf',
    Role: '',
    'Attendance Method': 'Computer',
    'Mac Address': '643150303E12,6C4B9096CA16',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Hofuf - Building A Main Entrance',
    HOD: 'Mohamad Almhdy Attya Mohamad',
    'Early Check-In Allowed': 'No',
    Status: 'Active',
  },
  {
    'Employee No': '32262',
    Name: 'GULSHAH',
    Department: 'Facility Engineering Department',
    Branch: 'Dammam',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Dammam - AST Main Entrance',
    HOD: 'Ibrahim Abdulrahman Bousbait',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32257',
    Name: 'ISLAMISMAIL',
    Department: 'Pediatric Ward',
    Branch: 'Jubail',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Jubail - Transportation Office',
    HOD: 'NA',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32221',
    Name: 'MansourAlam',
    Department: 'General Housekeeping Department',
    Branch: 'Dammam',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Multi-Location',
    'Assigned Location':
      'Dammam - Main Building - (Right-wing), Dammam Main Building  (Left-wing), Dammam - OPD Entrance',
    HOD: 'Charito Reyes Guanzon',
    'Early Check-In Allowed': 'No',
    Status: 'Active',
  },
  {
    'Employee No': '32241',
    Name: 'MazunBepari',
    Department: 'General Housekeeping Department - Jubail',
    Branch: 'Jubail',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Jubail - OPD Entrance',
    HOD: 'NA',
    'Early Check-In Allowed': 'No',
    Status: 'Active',
  },
  {
    'Employee No': '32252',
    Name: 'MOHAMMEDELAWADY',
    Department: 'General Surgery',
    Branch: 'Hofuf',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Multi-Location',
    'Assigned Location':
      'Hofuf - Building B Main Entrance, Hofuf - Building A Main Entrance',
    HOD: 'NA',
    'Early Check-In Allowed': 'No',
    Status: 'Active',
  },
  {
    'Employee No': '32238',
    Name: 'RafiqueAdam',
    Department: 'Housing Department',
    Branch: 'Jubail',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Jubail - OPD Entrance',
    HOD: 'NA',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32216',
    Name: 'SHAHIDHOSSAIN',
    Department: 'General Housekeeping Department',
    Branch: 'Dammam',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Khalidiya - IT Main Entrance',
    HOD: 'Charito Reyes Guanzon',
    'Early Check-In Allowed': 'No',
    Status: 'Active',
  },
  {
    'Employee No': '32058',
    Name: 'ShimaaAlsaody',
    Department: 'General Medicine',
    Branch: 'Khobar',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Khobar - Building A Main Entrance',
    HOD: 'NA',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32251',
    Name: 'SohaibAbdulkhaleq',
    Department: 'Dental Center',
    Branch: 'Khobar',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Khobar - Building D Main Entrance',
    HOD: 'Isam Abdel Fatah ',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32263',
    Name: 'SohailUddin',
    Department: 'Facility Engineering Department',
    Branch: 'Dammam',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Multi-Location',
    'Assigned Location':
      'Dammam - Main Building - (Right-wing), Dammam - AST Main Entrance, Dammam Main Building  (Left-wing), Dammam - OR Building, Dammam - OPD Entrance',
    HOD: 'Ibrahim Abdulrahman Bousbait',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32210',
    Name: 'SUKINAHALABDULMUHSIN',
    Department: 'General Housekeeping Department',
    Branch: 'Hofuf',
    Role: '',
    'Attendance Method': 'Computer',
    'Mac Address': ' 643150303E12,6C4B9096CA16',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Hofuf - Building A Main Entrance',
    HOD: 'Mohamad Almhdy Attya Mohamad',
    'Early Check-In Allowed': 'No',
    Status: 'Active',
  },
  {
    'Employee No': '32237',
    Name: 'THANGADURAITHANGADURAI',
    Department: 'Office Of The Nursing Director',
    Branch: 'Khobar',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Khobar - Building A Main Entrance',
    HOD: 'NA',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32204',
    Name: 'UDHAYAKUMARRADHAKRISHNAN',
    Department: 'Office Of The Nursing Director',
    Branch: 'Hofuf',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Hofuf - Building B Main Entrance',
    HOD: 'Rochelle Seifert Abello',
    'Early Check-In Allowed': 'No',
    Status: 'Active',
  },
  {
    'Employee No': '32270',
    Name: 'WalaAlSaleh',
    Department: 'Respiratory Therapy',
    Branch: 'Khobar',
    Role: '',
    'Attendance Method': 'Location',
    'Mac Address': 'NA',
    'Location Type': 'Multi-Location',
    'Assigned Location':
      'Khobar - Building B Main Entrance, Khobar - Tower 1 Staff Entrance',
    HOD: 'Ahmad Ibrahim',
    'Early Check-In Allowed': 'Yes',
    Status: 'Active',
  },
  {
    'Employee No': '32208',
    Name: 'ZainabAlbueisa',
    Department: 'General Housekeeping Department',
    Branch: 'Hofuf',
    Role: '',
    'Attendance Method': 'Computer',
    'Mac Address': '643150303E12,6C4B9096CA16',
    'Location Type': 'Single-Location',
    'Assigned Location': 'Hofuf - Building A Main Entrance',
    HOD: 'Mohamad Almhdy Attya Mohamad',
    'Early Check-In Allowed': 'No',
    Status: 'Active',
  },
];
